# This is a basic workflow to help you get started with Actions

name: Actions for Java

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run check style
      uses: nikitasavinov/checkstyle-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: 'github-pr-check'
        tool_name: 'testtool'
          
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          
      # Using Maven to build the program, RUN ALL TESTS, and pass all tests
      - name: Build with Maven
        run: cd backend/server/ 
              |
             mvn --batch-mode --update-snapshots package
        
        
#   # Test coverage      
#   coverage:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Test and generate coverage
#       - uses: actions/checkout@v3
#       - name: Set up JDK 11
#         uses: actions/setup-java@v3
#         with:
#           java-version: '11'
#           distribution: 'adopt'
#       - run: mvn cobertura:cobertura
        
#       - uses: 5monkeys/cobertura-action@master
#         with:
#           path: ${project}/target/site/cobertura/index.html
#           repo_token: ${{ secrets.GITHUB_TOKEN }}
#           minimum_coverage: 75
  
